### ISSUE TITLE
Custom authentication with provider type IMAP:  Exception on response deserialization

### ISSUE THREAD

**Issue by flokle** [nylas/nylas-java#209]
**Describe the bug**
According to the specification, scopes for IMAP email accounts are optional.
See point 5 here: [Nylas Docs](https://developer.nylas.com/docs/api/v3/admin/#post-/v3/connect/custom)

If you call the customAuthentication API endpoint via the SDK with settings for an IMAP account and do not specify any scopes, the response will not contain any scopes either. This causes the json deserializer to throw an exception, as scopes are expected:

```
org.jboss.resteasy.spi.UnhandledException: com.squareup.moshi.JsonDataException: Required value 'scope' missing at $.data
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:82)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:147)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: com.squareup.moshi.JsonDataException: Required value 'scope' missing at $.data
        at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:105)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapter.fromJson(KotlinJsonAdapter.kt:86)
        at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
        at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:58)
        at com.nylas.NylasClient.executeRequest(NylasClient.kt:331)
        at com.nylas.NylasClient.executePost(NylasClient.kt:263)
        at com.nylas.NylasClient.executePost$default(NylasClient.kt:252)
        at com.nylas.resources.Auth.customAuthentication(Auth.kt:103)
```

**To Reproduce**

```
Map<String, Object> settings = new HashMap<>();
		settings.put("imap_username", imapUsername);
		settings.put("imap_password", imapPassword);
		settings.put("imap_host", imapHost);
		settings.put("imap_port", imapPort);
		settings.put("smtp_host", smtpHost);
		settings.put("smtp_port", smtpPort);
CreateGrantRequest r = new CreateGrantRequest.Builder(AuthProvider.IMAP, settings).build();
		Grant grant = nylasClient.auth().customAuthentication(r).getData();
```

**Expected behavior**
According to the documentation: "If you don't define scopes in the request payload, Nylas uses the default scopes set on the relevant connector." Since there are no scopes on the imap connector (at least i cant specify any within the nylas dashboard), scopes should be optional on response and the SDK should be able to handle this.

**SDK Version:**
2.1.0

**Additional context**
Providing some scopes, e.g.: 
```
CreateGrantRequest r = new CreateGrantRequest.Builder(AuthProvider.IMAP, settings)
				.scopes(List.of("Mail.Read", "User.Read", "offline_access")).build();
```

 is a workaround.

**Comment by mrashed-dev** [comment]
@flokle Thanks for finding this issue! We will work on a fix 😄

**Comment by mrashed-dev** [comment]
@flokle this issue has been resolved by @atejada! This fix will be included in next week's SDK release 👍🏼.
