### ISSUE TITLE
Using internal api of OkHttp stops us from using newer version of OkHttp

### ISSUE THREAD

**Issue by jzinedine** [nylas/nylas-java#48]
**Describe the bug**
Using internal api of OkHttp stops us from using newer version of OkHttp
https://github.com/nylas/nylas-java/blob/5e79d0733c8997b01ef829538858d880ebf73e7b/src/main/java/com/nylas/HttpLoggingInterceptor.java#L115-L115

```
import okhttp3.internal.http.HttpHeaders
...
  + " resBodySize=" + HttpHeaders.contentLength(response)
```

HttpHeaders is part of internal api of OkHttp and should not be used in the sdk.

**To Reproduce**
Create a project, add nylas sdk as dependency and override OkHttp in your project, calling methods like 
account.events().list().fetchAll()
ends up with such stacktrace:
```Exception in thread "main" java.lang.NoSuchMethodError: okhttp3.internal.http.HttpHeaders.contentLength(Lokhttp3/Response;)J
	at com.nylas.HttpLoggingInterceptor.logResponse(HttpLoggingInterceptor.java:115)
	at com.nylas.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:73)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at com.nylas.AddVersionHeadersInterceptor.intercept(AddVersionHeadersInterceptor.java:24)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.nylas.NylasClient.executeRequest(NylasClient.java:170)
	at com.nylas.NylasClient.executeRequestWithAuth(NylasClient.java:153)
	at com.nylas.NylasClient.executeGet(NylasClient.java:112)
	at com.nylas.RestfulDAO.fetchQuery(RestfulDAO.java:56)
	at com.nylas.RemoteCollection.fetchSet(RemoteCollection.java:71)
	at com.nylas.RemoteCollection.fetchAll(RemoteCollection.java:58)```

```
// Helps us with reproducing the error :)
```

**Expected behavior**
Please remove HttpHeaders references from the sdk.

**SDK Version:**
The most recent version 1.11 and previous ones

**Comment by mrashed-dev** [comment]
@jzinedine Thank you for your patience, [Nylas Java SDK v1.11.2](https://github.com/nylas/nylas-java/releases/tag/v1.11.2) has been released containing the removal of the internal library!

**Comment by jzinedine** [comment]
@mrashed-dev Thank you very much Mostafa!
